web:
  build: ./web
  expose:
    - "8000"
  volumes:
    - ./web:/usr/src/app
  env_file: .env
  command: /usr/local/bin/gunicorn -w 2 -b :8000 app:app  --config /usr/src/app/gunicorn.py

nginx:
  build: ./nginx/
  ports:
    - "80:80"
  volumes:
    - /www/static
  volumes_from:
    - web
  links:
    - web:web

