"""empty message

Revision ID: 037c00dc243e
Revises: e80a84a4fc21
Create Date: 2016-11-09 13:53:18.390769

"""

# revision identifiers, used by Alembic.
revision = '037c00dc243e'
down_revision = 'e80a84a4fc21'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('cat_name', sa.String(), nullable=True))
    op.add_column('items', sa.Column('cat_time', sa.Integer(), nullable=True))
    op.drop_column('items', 'time_cat')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('time_cat', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('items', 'cat_time')
    op.drop_column('items', 'cat_name')
    ### end Alembic commands ###
