"""empty message

Revision ID: 07edccf19ce5
Revises: ddfe354b7b46
Create Date: 2016-11-15 22:08:44.509592

"""

# revision identifiers, used by Alembic.
revision = '07edccf19ce5'
down_revision = 'ddfe354b7b46'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles_users')
    ### end Alembic commands ###
