"""empty message

Revision ID: 282572a1df29
Revises: ad49ece22999
Create Date: 2016-12-04 20:42:07.241154

"""

# revision identifiers, used by Alembic.
revision = '282572a1df29'
down_revision = 'ad49ece22999'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'playlists', 'tags', ['tag_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'playlists', type_='foreignkey')
    ### end Alembic commands ###
