"""empty message

Revision ID: 3c75901ec14b
Revises: 282572a1df29
Create Date: 2016-12-20 08:46:33.794179

"""

# revision identifiers, used by Alembic.
revision = '3c75901ec14b'
down_revision = '282572a1df29'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('mood', sa.String(), nullable=True))
    op.add_column('items', sa.Column('mood', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'mood')
    op.drop_column('channels', 'mood')
    # ### end Alembic commands ###
