"""empty message

Revision ID: 6ad53b29ece1
Revises: 3c75901ec14b
Create Date: 2016-12-20 08:49:20.006351

"""

# revision identifiers, used by Alembic.
revision = '6ad53b29ece1'
down_revision = '3c75901ec14b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('itunes_category', sa.String(), nullable=True))
    op.execute('UPDATE channels SET itunes_category=genre')
    op.drop_column('channels', 'genre')
    op.add_column('items', sa.Column('itunes_category', sa.String(), nullable=True))
    op.execute('UPDATE items SET itunes_category=genre')
    op.drop_column('items', 'genre')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('genre', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.execute('UPDATE channels SET genre=itunes_category')
    op.drop_column('items', 'itunes_category')
    op.add_column('channels', sa.Column('genre', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.execute('UPDATE items SET genre=itunes_category')
    op.drop_column('channels', 'itunes_category')
    # ### end Alembic commands ###
