"""empty message

Revision ID: 73728c0138b3
Revises: bbb3be1d4fbc
Create Date: 2016-11-15 22:04:31.214469

"""

# revision identifiers, used by Alembic.
revision = '73728c0138b3'
down_revision = 'bbb3be1d4fbc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'toto')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('toto', sa.VARCHAR(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
