"""empty message

Revision ID: 7402b654dc00
Revises: 037c00dc243e
Create Date: 2016-11-10 12:07:55.811647

"""

# revision identifiers, used by Alembic.
revision = '7402b654dc00'
down_revision = '037c00dc243e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rel_playlists_items',
    sa.Column('playlist_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rel_playlists_items')
    ### end Alembic commands ###
