"""empty message

Revision ID: 7ff33ed46468
Revises: f0a9ba1c1343
Create Date: 2017-01-06 20:21:12.032606

"""

# revision identifiers, used by Alembic.
revision = '7ff33ed46468'
down_revision = 'f0a9ba1c1343'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('country', sa.String(), nullable=True))
    op.add_column('channels', sa.Column('source', sa.String(), nullable=True))
    op.add_column('items', sa.Column('country', sa.String(), nullable=True))
    op.add_column('items', sa.Column('source', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'source')
    op.drop_column('items', 'country')
    op.drop_column('channels', 'source')
    op.drop_column('channels', 'country')
    # ### end Alembic commands ###
