"""empty message

Revision ID: 850c919f1c0c
Revises: 73728c0138b3
Create Date: 2016-11-15 22:06:01.585654

"""

# revision identifiers, used by Alembic.
revision = '850c919f1c0c'
down_revision = '73728c0138b3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles')
    ### end Alembic commands ###
