"""empty message

Revision ID: 87ac3196813c
Revises: 6ad53b29ece1
Create Date: 2016-12-20 09:46:59.224081

"""

# revision identifiers, used by Alembic.
revision = '87ac3196813c'
down_revision = '6ad53b29ece1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('author_', sa.String(), nullable=True))
    op.add_column('channels', sa.Column('description_', sa.String(), nullable=True))
    op.add_column('channels', sa.Column('image', sa.String(), nullable=True))
    op.add_column('channels', sa.Column('image_', sa.String(), nullable=True))
    op.add_column('channels', sa.Column('itunes_category_', sa.String(), nullable=True))
    op.add_column('channels', sa.Column('language_', sa.String(), nullable=True))
    op.add_column('channels', sa.Column('last_build_date_', sa.DateTime(), nullable=True))
    op.add_column('channels', sa.Column('link_', sa.String(), nullable=True))
    op.add_column('channels', sa.Column('title', sa.String(), nullable=True))
    op.add_column('channels', sa.Column('title_', sa.String(), nullable=True))
    op.execute('UPDATE channels SET description_=description, image=img_url, image_=img_url, itunes_category_=itunes_category, language_=language, link_=url, title_=name, title=name')
    op.drop_column('channels', 'link')
    op.drop_column('channels', 'name')
    op.drop_column('channels', 'itunes_category')
    op.drop_column('channels', 'language')
    op.drop_column('channels', 'img_url')
    op.drop_column('channels', 'url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('channels', sa.Column('img_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('channels', sa.Column('language', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('channels', sa.Column('itunes_category', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('channels', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('channels', sa.Column('link', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.execute('UPDATE channels SET img_url=image_, itunes_category=itunes_category_, language=language_, url=link_, name=title_')
    op.drop_column('channels', 'title_')
    op.drop_column('channels', 'title')
    op.drop_column('channels', 'link_')
    op.drop_column('channels', 'last_build_date_')
    op.drop_column('channels', 'language_')
    op.drop_column('channels', 'itunes_category_')
    op.drop_column('channels', 'image_')
    op.drop_column('channels', 'image')
    op.drop_column('channels', 'description_')
    op.drop_column('channels', 'author_')
    # ### end Alembic commands ###
