"""empty message

Revision ID: 8913eb2fd82d
Revises: 07edccf19ce5
Create Date: 2016-11-17 20:16:17.066996

"""

# revision identifiers, used by Alembic.
revision = '8913eb2fd82d'
down_revision = '07edccf19ce5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'authenticated')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('authenticated', sa.BOOLEAN(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
