"""empty message

Revision ID: 9390797147fa
Revises: dab667a1d0f5
Create Date: 2016-12-30 15:07:44.089718

"""

# revision identifiers, used by Alembic.
revision = '9390797147fa'
down_revision = 'dab667a1d0f5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playlists', sa.Column('mood', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('playlists', 'mood')
    # ### end Alembic commands ###
