"""empty message

Revision ID: a7214b452c44
Revises: 8913eb2fd82d
Create Date: 2016-11-23 20:51:08.871154

"""

# revision identifiers, used by Alembic.
revision = 'a7214b452c44'
down_revision = '8913eb2fd82d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('genre', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'genre')
    ### end Alembic commands ###
