"""empty message

Revision ID: ad49ece22999
Revises: a7214b452c44
Create Date: 2016-12-04 20:18:18.948042

"""

# revision identifiers, used by Alembic.
revision = 'ad49ece22999'
down_revision = 'a7214b452c44'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('playlists', sa.Column('tag_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('playlists', 'tag_id')
    op.drop_table('tags')
    ### end Alembic commands ###
