"""empty message

Revision ID: ba926a2d1f53
Revises: 87ac3196813c
Create Date: 2016-12-20 10:45:08.244935

"""

# revision identifiers, used by Alembic.
revision = 'ba926a2d1f53'
down_revision = '87ac3196813c'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('audio_url_', sa.String(), nullable=True))
    op.add_column('items', sa.Column('description_', sa.String(), nullable=True))
    op.add_column('items', sa.Column('duration_', sa.Integer(), nullable=True))
    op.add_column('items', sa.Column('itunes_category_', sa.String(), nullable=True))
    op.add_column('items', sa.Column('pubdate_', postgresql.TIMESTAMP(), nullable=True))
    op.add_column('items', sa.Column('title', sa.String(), nullable=True))
    op.add_column('items', sa.Column('title_', sa.String(), nullable=True))
    op.execute('UPDATE items SET title_=name, title=name, description_=description, duration_=duration, itunes_category_=itunes_category, audio_url_=audio_url, pubdate_=published')
    op.drop_column('items', 'audio_url')
    op.drop_column('items', 'itunes_category')
    op.drop_column('items', 'published')
    op.drop_column('items', 'duration')
    op.drop_column('items', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('items', sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('items', sa.Column('published', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('items', sa.Column('itunes_category', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('items', sa.Column('audio_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.execute('UPDATE items SET name=title_, duration=duration_, published=pubdate_, audio_url=audio_url_')
    op.drop_column('items', 'title_')
    op.drop_column('items', 'title')
    op.drop_column('items', 'pubdate_')
    op.drop_column('items', 'itunes_category_')
    op.drop_column('items', 'duration_')
    op.drop_column('items', 'description_')
    op.drop_column('items', 'audio_url_')
    # ### end Alembic commands ###
