"""empty message

Revision ID: bbb3be1d4fbc
Revises: d533dbcd4600
Create Date: 2016-11-10 16:03:04.264144

"""

# revision identifiers, used by Alembic.
revision = 'bbb3be1d4fbc'
down_revision = 'd533dbcd4600'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_playlist_item_uc', 'rel_playlists_items', ['playlist_id', 'item_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_playlist_item_uc', 'rel_playlists_items', type_='unique')
    ### end Alembic commands ###
