"""empty message

Revision ID: d533dbcd4600
Revises: 7402b654dc00
Create Date: 2016-11-10 15:48:26.258673

"""

# revision identifiers, used by Alembic.
revision = 'd533dbcd4600'
down_revision = '7402b654dc00'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('toto', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'toto')
    ### end Alembic commands ###
