"""empty message

Revision ID: dab667a1d0f5
Revises: ba926a2d1f53
Create Date: 2016-12-20 18:07:31.290085

"""

# revision identifiers, used by Alembic.
revision = 'dab667a1d0f5'
down_revision = 'ba926a2d1f53'

from alembic import op
from flask.ext.sqlalchemy import SQLAlchemy
from parser.podmood import PodMood

db = SQLAlchemy()


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    podmood = PodMood('moods.xlsx')

    for iCat in podmood.mapping:
        op.execute("UPDATE channels SET mood='"+podmood.mapping[iCat]+"' WHERE itunes_category_='"+iCat+"'")
        op.execute("UPDATE items    SET mood='"+podmood.mapping[iCat]+"' WHERE itunes_category_='"+iCat+"'")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
