"""empty message

Revision ID: ddfe354b7b46
Revises: 850c919f1c0c
Create Date: 2016-11-15 22:07:45.543291

"""

# revision identifiers, used by Alembic.
revision = 'ddfe354b7b46'
down_revision = '850c919f1c0c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('confirmed_at', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'users', ['email'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'confirmed_at')
    op.drop_column('users', 'active')
    ### end Alembic commands ###
