"""empty message

Revision ID: e42dc4ac24fb
Revises: 7ff33ed46468
Create Date: 2017-01-12 09:24:22.699794

"""

# revision identifiers, used by Alembic.
revision = 'e42dc4ac24fb'
down_revision = '7ff33ed46468'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('itunes_category_', sa.String(), nullable=True),
    sa.Column('mood', sa.String(), nullable=True),
    sa.Column('mood_image', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    op.execute("INSERT INTO moods (itunes_category_, mood) SELECT DISTINCT itunes_category_, mood FROM channels")
    op.execute("UPDATE channels SET mood = (SELECT mood FROM moods WHERE moods.itunes_category_=channels.itunes_category_)")
    op.execute("UPDATE items SET mood = (SELECT mood FROM moods WHERE moods.itunes_category_=items.itunes_category_)")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('moods')
    # ### end Alembic commands ###
