"""empty message

Revision ID: e80a84a4fc21
Revises: aca641ae79d2
Create Date: 2016-11-09 08:34:15.330419

"""

# revision identifiers, used by Alembic.
revision = 'e80a84a4fc21'
down_revision = 'aca641ae79d2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    # migrate_engine.execute('ALTER TABLE items ALTER COLUMN duration TYPE INTEGER USING duration::INTEGER')
    op.alter_column('items', 'duration', existing_type=sa.VARCHAR(), type_=sa.Integer(), postgresql_using='duration::integer')
    op.add_column('items', sa.Column('time_cat', sa.Integer(), nullable=True))
    op.drop_column('items', 'item_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'duration', existing_type=sa.Integer(), type_=sa.VARCHAR())
    op.add_column('items', sa.Column('item_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('items', 'time_cat')
    ### end Alembic commands ###
