"""empty message

Revision ID: f0a9ba1c1343
Revises: 9390797147fa
Create Date: 2017-01-03 17:30:52.478741

"""

# revision identifiers, used by Alembic.
revision = 'f0a9ba1c1343'
down_revision = '9390797147fa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('image', sa.String(), nullable=True))
    op.execute('UPDATE items SET image=(SELECT image fROM channels WHERE id=items.channel_id)')    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'image')
    # ### end Alembic commands ###
